### ISSUE TITLE
Unable to start dynamoc_web

### ISSUE THREAD

**Issue by serendipity30** [ieiayaobb/dynamoc_web#1]
I changed port from 8080 to 8090 by updating file dynamoc_web-master/config/index.js and server started with below errors & nothing starts at port 8090

james@seren73:/opt/dynamoc_web-master$ npm run dev

> dynamoc_web@1.0.0 dev /opt/dynamoc_web-master
> node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 2 errors                                                                                                                   10:56:06 PM

 error  in ./src/App.vue

Module build failed: Error:

Vue packages version mismatch:

- vue@2.2.6
- vue-template-compiler@2.3.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/opt/dynamoc_web-master/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/dynamoc_web-master/node_modules/vue-loader/lib/parser.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

 @ ./src/main.js 6:0-24
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Framework.vue

Module build failed: Error:

Vue packages version mismatch:

- vue@2.2.6
- vue-template-compiler@2.3.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/opt/dynamoc_web-master/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/dynamoc_web-master/node_modules/vue-loader/lib/parser.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

 @ ./src/routes.js 4:13-46
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8090

I'm running it on CentOS 7.3. Any idea how to fix this error? 

Thanks!

**Comment by ieiayaobb** [comment]
I just updated the version of vue-template-complier, please check the latest 'package.json'
